//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarModels()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int IdCarModels { get; set; }
        public string Model { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<double> Acceleration { get; set; }
        public Nullable<int> MaxSpeed { get; set; }
        public Nullable<int> YearOfIssue { get; set; }
        public string Image { get; set; }
        public string ImageAbove { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
    }
}
