//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.BeetwenCarsClients = new HashSet<BeetwenCarsClients>();
        }
    
        public string RegistrationNumber { get; set; }
        public int IdBrand { get; set; }
        public int IdCarModels { get; set; }
        public int IdColor { get; set; }
        public int IdCarcassType { get; set; }
        public int Availability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeetwenCarsClients> BeetwenCarsClients { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual CarcassType CarcassType { get; set; }
        public virtual CarModels CarModels { get; set; }
        public virtual Color Color { get; set; }
    }
}
